/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MiniGrafDb {
  /** Open a file-backed database. Throws on error. */
  constructor(path: string)
  /** Open an in-memory database. Throws on error. */
  static inMemory(): MiniGrafDb
  /** Execute a Datalog string. Returns a JSON string. Throws on error. */
  execute(datalog: string): string
  /** Flush the WAL to disk. Throws on error. */
  checkpoint(): void
}
