/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MiniGrafDb {
  /**
   * Open a file-backed database. Throws on error.
   *
   * Only one handle per file may be open in a process at a time. Call
   * `close()` before reopening the same path — see `close()`.
   */
  constructor(path: string)
  /** Open an in-memory database. Throws on error. */
  static inMemory(): MiniGrafDb
  /** Execute a Datalog string. Returns a JSON string. Throws on error. */
  execute(datalog: string): string
  /** Flush the WAL to disk. Throws on error. */
  checkpoint(): void
  /**
   * Close the database, releasing its file lock immediately.
   *
   * Letting a `MiniGrafDb` go out of scope is **not** enough to release the
   * file. JavaScript has no deterministic destructor: the object merely
   * becomes unreachable, and the underlying handle lives until V8 garbage
   * collects it — arbitrarily later, or never before the process exits.
   *
   * That matters because minigraf permits only one live handle per file per
   * process (two would each cache their own page table and corrupt each
   * other), so opening the same path again throws until the first handle is
   * really gone. `close()` is the only way to make that happen on demand.
   * Every other binding has the same escape hatch: UniFFI (Python, Java,
   * Swift) exposes `destroy()`, and the C API exposes `minigraf_close`.
   *
   * Call `checkpoint()` first if you need to know the WAL was compacted;
   * closing does that too, but cannot report a failure.
   *
   * Idempotent — closing an already-closed database is a no-op. Every other
   * method throws afterwards.
   *
   * ```js
   * const db = new MiniGrafDb(path)
   * db.execute('(transact [[:bob :name "Bob"]])')
   * db.checkpoint()
   * db.close()
   *
   * const db2 = new MiniGrafDb(path) // fine: the first handle is gone
   * ```
   */
  close(): void
}
