/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** The rows of one query answer, in batches. Iterable over rows. */
export declare class Cursor {
  /** The `:find` variables, in column order. */
  vars(): Array<string>
  /**
   * The next batch of at most `maxRows` rows (0 counts as 1), as a JSON
   * array of rows encoded like `execute()`'s `results`; `null` at the end
   * or after `close()`. A batch is never empty.
   */
  nextBatch(maxRows: number): string | null
  /** Release the cursor. Later `nextBatch()` calls return `null`. */
  close(): void
}

/**
 * A forward-only stream of fact records from `MiniGrafDb.factLog`.
 * Iterable over records.
 */
export declare class FactLog {
  /**
   * The next batch of at most `maxRecords` records (0 counts as 1); `null`
   * at the end or after `close()`. A batch is never empty.
   */
  nextBatch(maxRecords: number): Array<FactRecord> | null
  /** Stop reading and release the database. */
  close(): void
}

/**
 * Builds a new database file from fact records, keeping their transaction
 * and valid-time bounds. The file is built at `<path>.partial` and renamed
 * into place by `finish()`. Call `close()` (for example in `finally`) to
 * abandon an unfinished build; it is a no-op after `finish()`.
 */
export declare class LogWriter {
  /** Start building a new database at `path` (STG-043 if it exists). */
  static create(path: string, options?: OpenOptions | undefined | null): LogWriter
  /** Append one record. A rejected record changes nothing. */
  append(record: FactRecord): void
  /**
   * Append `records` in order, stopping at the first rejected one. Its
   * error ends with `(batch index N)`; the records before it stay appended.
   */
  appendBatch(records: Array<FactRecord>): void
  /** Close the open transaction and raise the counter to `txCount`. */
  advanceTxCount(txCount: bigint): void
  /** The highest `txCount` appended or advanced to. */
  txCount(): bigint
  /**
   * Commit every record and rename the file into place. Later calls throw
   * API-018.
   */
  finish(): void
  /**
   * Abandon an unfinished build, deleting `<path>.partial`. A no-op after
   * `finish()` or `close()`.
   */
  close(): void
  /** `false` once `finish()` or `close()` has been called. */
  isOpen(): boolean
}

export declare class MiniGrafDb {
  /**
   * Open a file-backed database. Throws on error.
   *
   * Only one handle per file may be open in a process at a time. Call
   * `close()` before reopening the same path — see `close()`.
   */
  constructor(path: string)
  /** Open an in-memory database. Throws on error. */
  static inMemory(): MiniGrafDb
  /**
   * Open a file-backed database with `options`. Throws on error.
   *
   * `MiniGrafDb.openWithOptions(path, { readOnly: true })` opens the file
   * read-only: any number of read-only handles can share it, and writes
   * throw API-014.
   */
  static openWithOptions(path: string, options?: OpenOptions | undefined | null): MiniGrafDb
  /** Open a cursor over a `(query ...)`. Its answer is fixed when it opens. */
  query(datalog: string): Cursor
  /**
   * Stream every fact record that `filter` keeps. Checkpoints wait until
   * the log is closed or read to the end.
   */
  factLog(filter?: FactFilter | undefined | null): FactLog
  /** The transaction counter that `:as-of N` compares against. */
  currentTxCount(): bigint
  /** Execute a Datalog string. Returns a JSON string. Throws on error. */
  execute(datalog: string): string
  /** Flush the WAL to disk. Throws on error. */
  checkpoint(): void
  /**
   * Close the database, releasing its file lock immediately.
   *
   * Letting a `MiniGrafDb` go out of scope is **not** enough to release the
   * file. JavaScript has no deterministic destructor: the object merely
   * becomes unreachable, and the underlying handle lives until V8 garbage
   * collects it — arbitrarily later, or never before the process exits.
   *
   * That matters because minigraf permits only one live handle per file per
   * process (two would each cache their own page table and corrupt each
   * other), so opening the same path again throws until the first handle is
   * really gone. `close()` is the only way to make that happen on demand.
   * Every other binding has the same escape hatch: UniFFI (Python, Java,
   * Swift) exposes `destroy()`, and the C API exposes `minigraf_close`.
   *
   * Call `checkpoint()` first if you need to know the WAL was compacted;
   * closing does that too, but cannot report a failure.
   *
   * Idempotent — closing an already-closed database is a no-op. Every other
   * method throws afterwards.
   *
   * ```js
   * const db = new MiniGrafDb(path)
   * db.execute('(transact [[:bob :name "Bob"]])')
   * db.checkpoint()
   * db.close()
   *
   * const db2 = new MiniGrafDb(path) // fine: the first handle is gone
   * ```
   */
  close(): void
}

/**
 * Which records a fact log returns. Every field is optional; the ones that
 * are set must all match.
 */
export interface FactFilter {
  /** Keep these attributes (combined with `attributePrefixes`, either matches). */
  attributes?: Array<string>
  /** Keep attributes starting with one of these, such as `":ingestion/"`. */
  attributePrefixes?: Array<string>
  /** Keep these entity UUID strings. */
  entities?: Array<string>
  /** Lowest `txCount` kept (inclusive). */
  txFrom?: bigint
  /** Highest `txCount` kept (inclusive). */
  txTo?: bigint
  /** `"tx"` (default: ascending `txCount`) or `"storage"` (cheapest order). */
  order?: 'tx' | 'storage'
  /** In `"tx"` order, the most records held in memory at once. */
  window?: number
}

/**
 * One fact-log record: an assertion or a retraction, with its transaction
 * and valid-time bounds. `validTo` = 9223372036854775807n is forever.
 */
export interface FactRecord {
  /** The entity UUID string. */
  entity: string
  attribute: string
  value: FactValue
  txCount: bigint
  txId: bigint
  validFrom: bigint
  validTo: bigint
  asserted: boolean
}

/**
 * A fact value with its type kept: `type` is one of `"string"`, `"integer"`
 * (`value` a bigint), `"float"`, `"boolean"`, `"ref"` (an entity UUID
 * string), `"keyword"` or `"null"` (no `value`).
 */
export interface FactValue {
  type: 'string' | 'integer' | 'float' | 'boolean' | 'ref' | 'keyword' | 'null'
  value?: string | number | bigint | boolean
}

/**
 * Options for `MiniGrafDb.openWithOptions` and `LogWriter.create`. Every field
 * is optional; an absent field keeps the Rust default.
 */
export interface OpenOptions {
  /** Open read-only: shared lock, nothing written, writes throw API-014. */
  readOnly?: boolean
  /** Pages (4 KB each) in the page cache. Default 256. */
  pageCacheSize?: number
  /** Open even when the filesystem cannot lock files. Default false. */
  allowUnlocked?: boolean
  /** WAL entries before an automatic checkpoint. Default 1000. */
  walCheckpointThreshold?: number
  /** Facts a recursive rule may derive per iteration. Default 1,000,000. */
  maxDerivedFacts?: number
  /** Rows a query may return. Default 1,000,000. */
  maxResults?: number
  /** WAL durability: `"full"` (default) or `"normal"`. */
  synchronous?: 'full' | 'normal'
}
